### ISSUE TITLE
Rcpp error for Webb weights with few clusters

### ISSUE THREAD

**Issue by fschoner** [s3alfisc/fwildclusterboot#11]
First of all thanks for the great package! 

I ran into an issue trying to use Webb weights on a dataset with only 4 clusters. Given that my data are confidential, I replicated it using the voters data from your vignette. If I articificially keep the numbers of clusters in the voters data low, I get the exact same error. Interestingly, the cutoff determining whether or not the code works seems to be 13 clusters.

Running 
``` 
library(fwildclusterboot)
library(fixest)
library(data.table)

data(voters)
clu <- sample(unique(voters$group_id1), size = 13, replace = FALSE)
voters <- setDT(voters)[group_id1 %in% clu, ] 

#fwrite(voters, str_c(path_out_data, length(clu), "stata_voters.csv"))

feols_fit <- feols(
  proposition_vote ~ treatment  + log_income | Q1_immigration + Q2_defense,
  data = voters
  )

# bootstrap inference via boottest()
feols_boot <- boottest(
  feols_fit, clustid = c("group_id1"), B = 9999, param = "treatment",
  type = "webb"
  )
```
yields 

```
Error in eigenMapMatMult(as.matrix(K_a), v, nthreads) : 
  Object 'v' not found
```
If I use 14 clusters, it runs through smoothly. Another thing to note is that the procedure **works using Stata/SE 16.1** with the following code:

```
set more off
capture log close 
version 16

import delimited using "13stata_voters.csv"

reg proposition_vote treatment log_income i.q1_immigration i.q2_defense
boottest treatment, reps(9999) weighttype(webb)
```

I'll attach excerpts of R's session info below. I've updated the packages loaded only today.

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

other attached packages: [1] data.table_1.14.0      fixest_0.8.1           fwildclusterboot_0.3.4  loaded via a namespace (and not attached):  [1] Rcpp_1.0.6               lattice_0.20-41          gtools_3.8.2             zoo_1.8-8                Matrix.utils_0.9.8        [6] grid_4.0.3               nlme_3.1-149             dreamerr_1.2.3           RcppArmadillo_0.10.1.2.0 Matrix_1.2-18            [11] generics_0.1.0           collapse_1.5.3           sandwich_3.0-1           grr_0.9.5                Formula_1.2-4            [16] tools_4.0.3              RcppEigen_0.3.3.7.0      numDeriv_2016.8-1.1      parallel_4.0.3           compiler_4.0.3

```

**Comment by s3alfisc** [comment]
Hi! 
Thanks for making me aware of this and your very helpful exposition of the problem - you have found a veritable bug! 
I have fixed it in the current development version. 
What happened was the following: the weights matrix v was not generated due to an ill-specified if-clause (hence the rcpp function using it could not find the weights matrix). The problematic if-clause evaluates to TRUE only when 2^(number of clusters) < B, and in your case, 2^4 < 2^13 = 8192 < B = 9999. Given that 2^14 = 16384 > 9999, that explains why you did not run into an error with 14 clusters! 

If I run your example using the current development version (updated ~ 5 minutes ago) with four clusters, everything works as it should: 

```
library(fwildclusterboot)
library(fixest)
library(data.table)

data(voters)
clu <- sample(unique(voters$group_id1), size = 4, replace = FALSE)
voters <- setDT(voters)[group_id1 %in% clu, ] 

#fwrite(voters, str_c(path_out_data, length(clu), "stata_voters.csv"))

feols_fit <- feols(
  proposition_vote ~ treatment  + log_income | Q1_immigration + Q2_defense,
  data = voters
)

# bootstrap inference via boottest()
feols_boot <- boottest(
  feols_fit, clustid = c("group_id1"), B = 9999, param = "treatment",
  type = "webb"
)
summary(feols_boot)

#> summary(feols_boot)
#boottest.fixest(object = feols_fit, clustid = c("group_id1"), 
 #   param = "treatment", B = 9999, type = "webb")
	
# Observations: 36
# Bootstr. Type: webb
# Clustering: 1-way
# Confidence Sets: 95%
# Number of Clusters: 4
 
#      term estimate statistic p.value conf.low conf.high
#1 treatment    0.301      2.41   0.294   -0.662     0.875
```

Best, Alex

**Comment by fschoner** [comment]
Dear Alex,

thank you so much for solving this issue so quickly - everything works fine with the Webb-weights now. 

I have two related questions. When comparing the results of the Stata implementation with the R package, results differ quite substantially for the Rademacher weights (they are closer to each other for the webb weights while differences persist). If I use the dataset generated by the following code

```
set.seed(123)
data(voters)
clu <- sample(unique(voters$group_id1), size = 4, replace = FALSE)
voters <- setDT(voters)[group_id1 %in% clu, ] 
```
I receive the following sequence of p-values by running 
```
feols_boot <- boottest(
  feols_fit, clustid = c("group_id1"), B = 9999, param = "treatment"
  )
feols_boot$p_val
```
repeatedly:
```
0.25, 0.125, 0.0625, 0
```
while Stata yields
```
0.2483, 0.2400, 0.2491, 0.2469
```
Q1: Following [Cameron & Miller, 2015, p. 27](http://jhr.uwpress.org/content/50/2/317.refs), 4 clusters should yield 2^{4-1} = 8 possible values of the bootstrap t-statistic. Thus, the **minimum** possible p-value should be 0.125 = 1/8 with the true p-value being strictly smaller but unknown. Why are values such as 0.0625 and 0 possible? As I've just begun reading up on the wild cluster bootstrap, any pointers and corrections are much appreciated!

Q2: The Stata-output seems to always be roughly equal to 0.25, but never exactly so. Do you know why this is the case? 

Best,
Flo

**Comment by s3alfisc** [comment]
Hi Flo, 

Thanks for comparing the behavior of the Stata and R implementations, that is truly valuable! I have one quick comment on Q2: 

I believe (but have not checked it) that stata::boottest uses equal-tailed p-values when the number of iterations B is small (see the [Fast & Wild paper](https://journals.sagepub.com/doi/full/10.1177/1536867X19830877), equation 19). Note that effectively, B = 16 with 4 clusters and Rademacher weights in both the Stata and R implementations. 
The R version currently does not switch to equal-tailed p-values - maybe this can explain the discrepancy between the R and Stata output? What happens if you force the Stata p-values to be symmetric via the ptype(symmetric) syntax? Similar discrepancies between R and Stata should then also arise when using Mammen weights (I will check this later today myself). For Webb weights, Stata probably switches back to to symmetric p-values, as it does not constrain B. 

Best, Alex

**Comment by s3alfisc** [comment]
Hi Flo, 

Sorry for taking some time to get back to you! 

Regarding Q1: 

My first "bug fix" to your initial post solved some, but not all issues for very small numbers of clusters, and you have spotted another one in Q1. I have tried to address it in commit 180e5cfb9ec1beb7b6fb0c8d582a0003566b9ea5. 
For rademacher and mammen weights, if 2^(number of clusters) < B, the trouble-making if-clause that should initiate full enumeration was not binding - in consequence, not every feasible t-statistics was generated & some were (randomly) oversampled with B = 2^(number of clusters), leading to theoretically impossible p-values for (deterministic) full enumeration (e.g. 0.0625 with N_G = 4).

I have added unit tests for correct behavior in inst/tinytest/test_seed.R and ./test_small_n_cluster.R. If you have time to have a look at them, I'd be very happy about feedback. Also, if you happen to have suggestions for further unit tests centering for cases of very few clusters, please let me know! 

I have also added an internal seed to `boottest()` for cases where the user does not provide it - now repeatedly calling `boottest()` without a provided seed generates the same test statistics. I am not certain about this feature, so if you have a preference, please let me know.

Thanks for your feedback! 
Alex
