### ISSUE TITLE
bayesian bootstrap

### ISSUE THREAD

**Issue by soodoku** [s3alfisc/fwildclusterboot#118]
Dear Alex,

There are some collinearity issues that cause fwildclusterboot to fail. I think the options include --- ignore those samples (and report on those separately) or support bayesian bootstrap: https://twitter.com/instrumenthull/status/1487469316010389516?lang=en

**Comment by s3alfisc** [comment]
Hi @soodoku , thanks for reporting! 

Do you have an example at hand so that I can reproduce this? Is this related to fixest dropping covariates in case of multicollinearity? My assumption was actually that collinearity should be handled smoothly (i.e. if the OLS package does not complain, `fwildclusterboot` shouldn't either. If it does, I would assume that something is off in my data processing scripts?

Fyi, in case you are not aware - I think the bayesian bootstrap is nowadays implemented in `sandwich`([link](https://sandwich.r-forge.r-project.org/reference/vcovBS.html)) and via the [fwb package](https://ngreifer.github.io/fwb/).
