### ISSUE TITLE
Problem with FELM formulas

### ISSUE THREAD

**Issue by ecrjak** [s3alfisc/fwildclusterboot#145]
I am encountering issues when running `boottest` after `felm` but only if I supply the `formula` argument indirectly via a formula object (which I do rather frequently in my workflow). When doing so I get an error message saying `Error in x$formula : object of type 'symbol' is not subsettable`

Here is an illustration using the example from the reference manual. Note that `felm` accepts both versions whereas `boottest` doesn't:

This works:
```
requireNamespace("lfe")
data(voters)
felm_fit <- felm(proposition_vote ~ treatment + ideology1 + log_income | Q1_immigration, data = voters)
boot1 <- boottest(felm_fit,
                  B = 9999,
                  param = "treatment",
                  clustid = "group_id1"
)
```

This doesn't work:
```
requireNamespace("lfe")
data(voters)
for.reg <- formula(proposition_vote ~ treatment + ideology1 + log_income | Q1_immigration)
felm_fit <- felm(for.reg, data = voters)
boot1 <- boottest(felm_fit,
                  B = 9999,
                  param = "treatment",
                  clustid = "group_id1"
)
```

Thanks a lot in advance for any help!

**Comment by s3alfisc** [comment]
Hi, boottest calls Formula::Formula internally. What happens if you specify your models via Formula::Formula instead of stats::Formula? I can't debug right now as not close to a laptop unfortunately.

**Comment by ecrjak** [comment]
Using `for.reg <- Formula::Formula(proposition_vote ~ treatment + ideology1 + log_income | Q1_immigration)`

produces the error message `Error in is.name(callee) && length(object) > 20 : 
  'length = 2' in coercion to 'logical(1)'`

It still creates `for.reg` but when I use this in `boottest`, I get the same error message as in my initial post `Error in x$formula : object of type 'symbol' is not subsettable` without creating `boot1`.

**Comment by s3alfisc** [comment]
Thanks, I'll take a closer look this weekend! :)

**Comment by ecrjak** [comment]
Hi. Just wanted to quickly check if there are already any updates :)

**Comment by s3alfisc** [comment]
Sorry, it was a busy week and when I had time, some other projects took priority. Will take a look tomorrow though!

**Comment by ecrjak** [comment]
Sorry, just wanted to quickly follow up on this again...

**Comment by s3alfisc** [comment]
Hi @ecrjak , 

I just took a look: the problem arises in [model_matrix.felm](https://github.com/s3alfisc/fwildclusterboot/blob/336bb574eba169ac0183317f01d0564791d8122f/R/model_matrix.R#L51).

```r
library("lfe")
data(voters)
for.reg <- formula(proposition_vote ~ treatment + ideology1 + log_income | Q1_immigration)
felm_fit <- felm(for.reg, data = voters)

model.matrix(felm_fit)
lfe:::model.matrix.felm(felm_fit)
```
Both `stats::model_matrix` and `lfe::model.matrix.felm` produce this error & I currently don't know best solve it within `fwildclusterboot`.

Basically, what happens is that `model.matrix` tries to access `lfe_fit$call$formula`, which returns `for.reg`, which is not a proper formula. 

But if you specify your model as 

```r
lfe_fit <- felm(formula = for.reg, data = voters)
#lfe_fit$call$formula <- for.reg

boot1 <- boottest(feols_fit,
                  B = 9999,
                  param = "treatment",
                  clustid = "group_id1"
)
```
i.e. if you name the formula argument, then boottest runs through, at least for me =) I hope that will work for you as well!


Last, I wanted to point you to the formidable `fixest` package, which does the same job as `lfe` but, in many ways, better (in case you are not yet aware of it). 

```r
library(fixest)
feols_fit <- feols(for.reg, data = voters)
boot1 <- boottest(feols_fit,
                  B = 9999,
                  param = "treatment",
                  clustid = "group_id1"
)

summary(boot1)
```

Is there a patricular reason for which you need to stick with `lfe`? The package is no longer developed and only maintained so that it remains on CRAN, and `fixest` really is superb (and works well with `fwildclusterboot`). 

And sorry for the delay! 

Best, Alex

**Comment by ecrjak** [comment]
Thanks so much for this! Indeed, when explicitly overwriting ``lfe_fit$call$formula`` with the initial formula, the code runs through without any error :)

There is no particular reason for sticking with the ``lfe`` package apart from my own laziness in re-writing the codes for many of my research projects. That said, it seems like ``fixest`` has a lot of interesting stuff to offer and it may be worth starting the transition if ``lfe`` is no longer developed as you say. Thanks for the nudge!
